FROM mcr.microsoft.com/devcontainers/javascript-node:1-18-bullseye

# Playwright dependencies
# TODO https://playwright.dev/docs/docker
# RUN apt-get update
# RUN apt-get install -y libnss3 \
#     libnspr4 \
#     libdbus \
#     libatk1 \
#     libatk \
#     libcups2 \
#     libdrm2 \
#     libxkbcommon0 \
#     libatspi2 \
#     libxcomposite1 \
#     libxdamage1 \
#     libxfixes3 \
#     libxrandr2 \
#     libgbm1 \
#     libasound2 

RUN yarn global add nx
